#! /bin/bash

rm -rf target && mkdir -p target/classes
CP=`lein classpath`
find src/java -name "*.java" | xargs javac -Xlint:unchecked -target 21 -source 21 -encoding utf8 -cp $CP -d target/classes -sourcepath src/java/
